// @flow

export type ReactNativeBasicStylesheet = $Exact<{
  // https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/StyleSheetTypes.js
  alignContent?:
    | 'flex-start'
    | 'flex-end'
    | 'center'
    | 'stretch'
    | 'space-between'
    | 'space-around',
  alignItems?: 'flex-start' | 'flex-end' | 'center' | 'stretch' | 'baseline',
  alignSelf?: 'auto' | 'flex-start' | 'flex-end' | 'center' | 'stretch' | 'baseline',
  aspectRatio?: number,
  backfaceVisibility?: string | number,
  backgroundColor?: string | number,
  borderBottomColor?: string | number,
  borderBottomLeftRadius?: number,
  borderBottomRightRadius?: number,
  borderBottomWidth?: number,
  borderColor?: string | number,
  borderLeftColor?: string | number,
  borderLeftWidth?: number,
  borderRadius?: number,
  borderRightColor?: string | number,
  borderRightWidth?: number,
  borderStyle?: string | number,
  borderTopColor?: string | number,
  borderTopLeftRadius?: number,
  borderTopRightRadius?: number,
  borderTopWidth?: number,
  borderWidth?: number,
  bottom?: string | number,
  color?: string | number,
  decomposedMatrix?: string | number,
  direction?: string | number,
  display?: string | number,
  elevation?: string | number,
  flex?: number,
  flexBasis?: string | number,
  flexDirection?: string | number,
  flexGrow?: number,
  flexShrink?: number,
  flexWrap?: string | number,
  fontFamily?: string,
  fontSize?: number,
  fontStyle?: 'normal' | 'italic',
  fontVariant?: $ReadOnlyArray<
    'small-caps' | 'oldstyle-nums' | 'lining-nums' | 'tabular-nums' | 'proportional-nums',
  >,
  fontWeight?: string | number,
  height?: string | number,
  includeFontPadding?: string | number,
  justifyContent?: string | number,
  left?: string | number,
  letterSpacing?: number,
  lineHeight?: number,
  margin?: string | number,
  marginBottom?: string | number,
  marginHorizontal?: string | number,
  marginLeft?: string | number,
  marginRight?: string | number,
  marginTop?: string | number,
  marginVertical?: string | number,
  maxHeight?: string | number,
  maxWidth?: string | number,
  minHeight?: string | number,
  minWidth?: string | number,
  opacity?: string | number,
  overflow?: 'visible' | 'hidden' | 'scroll',
  overlayColor?: string | number,
  padding?: string | number,
  paddingBottom?: string | number,
  paddingHorizontal?: string | number,
  paddingLeft?: string | number,
  paddingRight?: string | number,
  paddingTop?: string | number,
  paddingVertical?: string | number,
  position?: string | number,
  resizeMode?: string | number,
  right?: string | number,
  rotation?: string | number,
  scaleX?: number,
  scaleY?: number,
  shadowColor?: string | number,
  shadowOffset?: $FlowFixMe,
  shadowOpacity?: number,
  shadowRadius?: number,
  textAlign?: 'auto' | 'left' | 'right' | 'center' | 'justify',
  textAlignVertical?: 'auto' | 'top' | 'bottom' | 'center',
  textDecorationColor?: string | number,
  textDecorationLine?: string | number,
  textDecorationStyle?: string | number,
  textShadowColor?: string | number,
  textShadowOffset?: $FlowFixMe,
  textShadowRadius?: number,
  tintColor?: string | number,
  top?: string | number,
  transform?: $FlowFixMe,
  transformMatrix?: string | number,
  translateX?: number,
  translateY?: number,
  width?: string | number,
  writingDirection?: 'auto' | 'ltr' | 'rtl',
  zIndex?: number,
}>
